const:
  default-page-size: 20

file:
  directory: D:/2024-02/download/project_2

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: green.project_2.project

spring:
  application:
    name: project_2
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
# log4jdbc? ??? MariaDB ?? ??
    url: jdbc:log4jdbc:mariadb://localhost/team_todo
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB
# ?? ??? ? ?? ?? ?? ??
      max-request-size: 15MB

springdoc:
  swagger-ui:
# Swagger UI ??
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
# Swagger UI ?? ????2
    disabled: true
